title: 显影之尘
description: 博客通天下，淡墨书豪辞
author: 唐睿
github: https://github.com/tangrui
about: A full stack engineer, an architecture,
  a project coordinator and an entrepreneur, who is always learning.
disqus_shortname: dust-of-revelation
google_analytics: UA-57995-6
avatar_url: /static/img/avatar.png
permalink: :year/:title.html

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/tangruidotnet"
    - icon: fa-twitter
      link: "https://twitter.com/tangruidotnet"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/tangruidotnet/"
    - icon: fa-stack-exchange
      link: "https://stackexchange.com/users/449773/tangrui"
    - icon: fa-github
      link: "https://github.com/tangrui"

share:
  twitter_username: tangruidotnet
  fb_appid: 706359369537142

urls:
    - text: About Me
      url: /about/
      #    - text: My Projects
      #url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://www.tangrui.net"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
highlighter: rouge
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-youtube

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
